import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	topContainer: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 20 },
	margin20: { marginTop: 20 },
	orderIdText: { fontSize: 20, fontFamily: 'proxima-regular', color: '#464141' },
	orderIdValue: { fontSize: 36, fontFamily: 'proxima-bold' },
	dateAndPriceText: { fontSize: 16, fontFamily: 'proxima-regular', color: '#464141' },
	dateAndPriceValue: { fontSize: 19, fontFamily: 'proxima-bold' },
	marginTop10: { marginTop: 10 },
	statusContainer: { marginLeft: 35, marginTop: 20, flexDirection: 'row', justifyContent: 'space-between' },
	statusText: { color: '#f2893c', fontSize: 22, fontFamily: 'proxima-regular' },
	btn: { marginRight: 32, borderColor: '#000', borderWidth: 1, borderRadius: 5 },
	btnText: { fontFamily: 'proxima-regular', padding: 5 },
	customerContainer: { marginTop: 25, marginLeft: 35 },
	customerHeading: { fontSize: 22, fontFamily: 'proxima-bold', color: '#2d768a' },
	nameText: { fontSize: 24, fontFamily: 'proxima-regular', marginLeft: 10 },
	emailText: { fontSize: 22, fontFamily: 'proxima-regular', color: '#5b93af', marginLeft: 10 },
	addressContainer: { flexDirection: 'row', marginTop: 30, marginLeft: 30 },
	addressHeadingText: { fontSize: 20, fontFamily: 'proxima-bold', color: '#2d768a' },
	marginLeft10: { marginLeft: 10 },
	shippingAddressText: { fontSize: 16, fontFamily: 'proxima-bold', color: '#5e5961', marginTop: 10 },
	addressAndPhoneContainer: { flexDirection: 'row', marginTop: 10, },
	addressText: { fontSize: 18, fontFamily: 'proxima-regular', width: '90%', marginLeft: 10 },
	productsContainer: { marginTop: 30, marginLeft: 30 },
	paymentHeading: { fontSize: 20, fontFamily: 'proxima-bold', color: '#2d768a' },
	shippingElementContainer: { flexDirection: 'row', marginTop: 10, marginLeft: 10 },
	regularHeading: { fontSize: 18, fontFamily: 'proxima-regular' },
	boldText: { fontSize: 18, fontFamily: 'proxima-bold' },
	headingWrapper: { flexDirection: "row", justifyContent: 'space-between' },
	btmHeight: { height: 30 },
})